### ISSUE TITLE
"Packet larger than expected" Connection Error

### ISSUE THREAD

**Issue by CorruptedCodes** [Gerrygames/ViaRewind#10]
Every now and then my players are kicked for this console error: http://prntscr.com/i2w2z2. I couldn't trace this to any other plugin, so I assume it had to be ViaRewind, as this also hasn't happened before I installed it.

**Comment by Gerrygames** [comment]
Client and server version?

**Comment by CorruptedCodes** [comment]
Client Version is 1.7.10, Server is 1.8.8 Paper.

**Comment by Gerrygames** [comment]
Should be fixed by #11. The fix will be included in the next version.
