### ISSUE TITLE
Kicked error

### ISSUE THREAD

**Issue by spileur** [Gerrygames/ViaRewind#13]
Hello,
I have a problem. I am kicked from the server with the reason :
![screenshot_1](https://user-images.githubusercontent.com/18127771/35291127-a03e9e2c-006c-11e8-9758-7a9bdf907abf.png)

**Comment by Gerrygames** [comment]
Are you using the latest version?

**Comment by TheIntelloBox** [comment]
Same problem.

**Comment by Gerrygames** [comment]
Could anyone experiencing this issue provide some more info? It would be helpful if you provide the output of /viaversion dump. Also please enable /viaversion debug then try to join and send me the console output. Maybe the client log would help too (make sure to remove the session id).

**Comment by Gerrygames** [comment]
This issue should be fixed by now. If it is still present please reopen this issue and provide some more information (client and server log).
