### ISSUE TITLE
Kick on join

### ISSUE THREAD

**Issue by TWSSYesterday** [Gerrygames/ViaRewind#14]
Trying to join my 1.12.2 Paperspigot server using a 1.7.10 client.
Version of Via plugins: https://i.imgur.com/1CbCTMP.png
Same issue when on latest jenkins builds.
Paperspigot build number: 1317.
All startup logs indicate everything is okay, no verbose/logs that would indicate otherwise. When I try to join it shows me this in the latest log: https://pastebin.com/NQ3aZiS0

**Comment by Gerrygames** [comment]
Could you enable /viaversion debug and then send me your server log again?

**Comment by TWSSYesterday** [comment]
Yup, log is too big so I've added it as a gist, let me know if that helps:
https://gist.github.com/TWSSYesterday/7df60ea616b51ae8d73d159241b89c24#file-gistfile1-txt
This is the debug

**Comment by Gerrygames** [comment]
This seems to be an issue of ViaBackwards. Until 1.12.1 the client was sending a keep alive packet every second in the downloading terrain gui. In 1.12.2 this was removed. I will inform Mats about this.

**Comment by Gerrygames** [comment]
Could you try if this happens on a 1.12.1 server? For me this is not happening on both.

**Comment by TWSSYesterday** [comment]
Got a link to 1.12.1, does yive's tcpr separate them?

**Comment by TWSSYesterday** [comment]
Trying now.

**Comment by TWSSYesterday** [comment]
Works! Any way to get it on 1.12.2? I assume something needs updating via side.

**Comment by Gerrygames** [comment]
Pretty sure this has to be fixed by ViaBackwards then.

**Comment by TWSSYesterday** [comment]
Will 1.12.2 clients still be able to join and what not? I guess I can keep it like this until it's resolved.

**Comment by Gerrygames** [comment]
1.12.2 clients can connect to a 1.12.1 server with ViaVersion

**Comment by TWSSYesterday** [comment]
Hoorah, that's good enough for now lol

**Comment by Gerrygames** [comment]
Are you using any other plugin, which could modify keep alive packets? Mats and I are both unable to reproduce this. Could you provide the output of /viaversion dump?

**Comment by Matsv** [comment]
And could you try if this issue occurs for you on other versions than 1.7? (:

**Comment by TWSSYesterday** [comment]
Works fine on 1.11 client on 1.12.2 server.

**Comment by TWSSYesterday** [comment]
https://gist.github.com/anonymous/58427d49de2a2a691b9618b471f4183e

**Comment by TWSSYesterday** [comment]
I'm on discord if you want me to call to discuss or try live.

**Comment by Gerrygames** [comment]
I am not very fluent in english, so I am rather writing than talking. Did you try with only ViaVersion, ViaBackwards and ViaRewind?

**Comment by TWSSYesterday** [comment]
No, I've added the dump to the issue.

**Comment by Gerrygames** [comment]
Yes I saw the dump. Could you try if the issue also occurs without the other plugins? That would be helpful.

**Comment by Matsv** [comment]
Do you use Bungeecord?

**Comment by TWSSYesterday** [comment]
No BungeeCord, happens with no other plugins also.

**Comment by Gerrygames** [comment]
Are you using and client mods?

**Comment by TWSSYesterday** [comment]
No, basic minecraft, not even optifine.

**Comment by TheIntelloBox** [comment]
Always the same bug. Very very annoying. :c

**Comment by TWSSYesterday** [comment]
:/

**Comment by Matsv** [comment]
@TheIntelloBox could you give us your "/viaversion dump" output?

**Comment by Matsv** [comment]
@TWSSYesterday @TheIntelloBox Could you please try the [latest dev build](https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/) of ViaBackwards on 1.12.2, that should fix it! (:

**Comment by TWSSYesterday** [comment]
This is now fixed, thank you very much for your help!
