### ISSUE TITLE
TABlist bug.

### ISSUE THREAD

**Issue by TheIntelloBox** [Gerrygames/ViaRewind#15]
Hey,

1.7 : https://zupimages.net/up/18/04/h9ez.jpg
1.12 : https://zupimages.net/up/18/04/lzji.jpg

TabList plugin : Tablist.

Thanks.

**Comment by Gerrygames** [comment]
If you mean that the stuff above and beneath the players (header and footer) are missing, this did not exist in 1.7. If you mean the player names itself, you mentioned the wrong plugin. Could you provide info on which plugin you are using to add the prefixes to the player names?

**Comment by TheIntelloBox** [comment]
I'm using GroupManager and Essentials Chat.

**Comment by Gerrygames** [comment]
Could you try with this build?
https://puu.sh/zbxFg/a878f82ce4.jar

**Comment by TheIntelloBox** [comment]
I don't have my name in the tablist and there are not the ranks.

**Comment by MasterDash5** [comment]
This is an issue caused my 1.7's tab limit. This cannot be fixed

**Comment by Gerrygames** [comment]
MasterDash5 is absolutly right. The tablist should now work properly. The display names will not be shown. The normal name will always be used. If you want prefix and suffix you need to use scoreboard teams.
