### ISSUE TITLE
Memory leak or idk

### ISSUE THREAD

**Issue by lekting** [Gerrygames/ViaRewind#17]
Hello, i have a problem with that plugin. When i enable server he is eating 200-300 mb RAM, but after 30-50 minute online he eating a 1.7GB (1700MB) RAM! I'm created dump of memory and i saw this plugin.
Version: 1.0.14
![screenshot_4](https://user-images.githubusercontent.com/6453931/35585673-4aecd19c-0601-11e8-8425-31699dff6002.png)

**Comment by Gerrygames** [comment]
This is only 368B (Bytes). One MB (MegaByte) is 1000000B (Bytes).

**Comment by lekting** [comment]
![screenshot_5](https://user-images.githubusercontent.com/6453931/35585890-d8e1b242-0601-11e8-984e-b9f43c326c47.png)
Google

**Comment by lekting** [comment]
B in visualVM equals Bytes or bits?
![screenshot_6](https://user-images.githubusercontent.com/6453931/35586124-9e23039e-0602-11e8-88d6-9f085c0aa292.png)

**Comment by Gerrygames** [comment]
Oh, I was looking at the size of one, not the total amount. I will look into it. Did you try running the garbage collector? I think they may get collected by it.

**Comment by lekting** [comment]
Collector is already running, and i can saw in information memory jumps (100 than 500 and again)

**Comment by Gerrygames** [comment]
This is how java garbage collection works.
