### ISSUE TITLE
thrown splash potions in 1.8 texture

### ISSUE THREAD

**Issue by Govindass** [Gerrygames/ViaRewind#18]
Hello, I have found a bug when you throw a splash potion by right-clicking with it, you see it falling as water bottle instead of the real texture of potion.

**Comment by Gerrygames** [comment]
The only way to fix this would be to delay the spawn packet until the metadata packet is send. But this will not be implemented, sorry.

**Comment by Lmmb74** [comment]
Why don't you make it optional? You can implement it (with its respective warning), and make it false by default 😁.
