### ISSUE TITLE
Can't write books on 1.8.9

### ISSUE THREAD

**Issue by Govindass** [Gerrygames/ViaRewind#19]
on 1.8.9 in 1.11.2 server can't write books, you just open it and typing doesn't work

**Comment by Gerrygames** [comment]
This seems to be a clientside issue. You need to add another page for it to work. But the signing of the book isn't working. I am currently working on a fix for that.

**Comment by Gerrygames** [comment]
Oh, turns out it was not a clientside bug. I fixed it.

**Comment by Govindass** [comment]
thanks for fixing it! How can I get the fixed version of ViaRewind, can you release the update on spigotmc?
