### ISSUE TITLE
player heads texture is not shown in 1.8.9

### ISSUE THREAD

**Issue by Govindass** [Gerrygames/ViaRewind#20]
I have found that placed player head blocks do not show their texture to 1.8.9 players on 1.11.2 spigot, it just shows skeleton head instead

**Comment by akymakycar** [comment]
Yup... Same issue on 1.12.2 server. This totally breaks /heads on older versions of Minecraft :/

**Comment by Govindass** [comment]
I found that if you place the head it still has texture for player until the chunk unloads, looks like it doesn't send the texture correctly only when chunk loads with head in it
