### ISSUE TITLE
Sign bug 

### ISSUE THREAD

**Issue by artbnzz** [Gerrygames/ViaRewind#21]
Sign Bug player 1.12.X can see "" but player 1.8.X can't see "" (i do not input "" to the sign plugin automatic input "") please fixed. 
Server version : 1.12.2
![2018-02-04_06 09 56](https://user-images.githubusercontent.com/35456258/35772486-26d742d2-0972-11e8-9fc4-f9ae65d7a80b.png)

**Comment by Gerrygames** [comment]
Which plugin version are you using?

**Comment by artbnzz** [comment]
ViaRewind-1.1.1


________________________________
จาก: Gerrygames <notifications@github.com>
ส่ง: 4 กุมภาพันธ์ 2561 22:34
ถึง: Gerrygames/ViaRewind
สำเนาถึง: artbnzz; Author
ชื่อเรื่อง: Re: [Gerrygames/ViaRewind] Sign bug (#21)


Which plugin version are you using?
