### ISSUE TITLE
Horse cannot move on 1.8.9

### ISSUE THREAD

**Issue by artbnzz** [Gerrygames/ViaRewind#22]
Horse can ride but cannot move on 1.8.9
please fixed
Server : 1.12.2

**Comment by Gerrygames** [comment]
This can not be fixed on a protocol level. However I do plan on releasing a separate spigot plugin to fix this problem.

**Comment by artbnzz** [comment]
Thank you i'am waiting for new plugin to fixed horse move


________________________________
จาก: Gerrygames <notifications@github.com>
ส่ง: 4 กุมภาพันธ์ 2561 22:34
ถึง: Gerrygames/ViaRewind
สำเนาถึง: artbnzz; Author
ชื่อเรื่อง: Re: [Gerrygames/ViaRewind] Horse cannot move on 1.8.9 (#22)


This can not be fixed on a protocol level. However I do plan on releasing a separate spigot plugin to fix this problem.

**Comment by CreaModZ** [comment]
Hello @Gerrygames,

Do you have any idea how to fix this boat / horse problem?
I'd like to patch it on the Spigot side, or possibly via a plugin, but I do not know where to start. :p

Thank you.
