### ISSUE TITLE
Item Frame Item Glitch (1.7.10/1.8.8)

### ISSUE THREAD

**Issue by rowan-smith** [Gerrygames/ViaRewind#30]
https://gist.github.com/4832b508eab672f7f035b3f5f70b34b0

**In 1.7 and 1.8 when you place and item inside an Item Frame you can hit the item out
and you get the item but it doesn't disappear from the item frame, when you 
hit it again it breaks the frame and the item.**
https://gyazo.com/76042d0db9fa45084690ab0860ebe188

**Comment by Gerrygames** [comment]
Since 1.9 the server expects the client to update the item frame itself. There is no easy way to fix this issue.
