### ISSUE TITLE
Anvil GUI Wrong Rename Level (1.7.10)

### ISSUE THREAD

**Issue by rowan-smith** [Gerrygames/ViaRewind#33]
https://gist.github.com/4832b508eab672f7f035b3f5f70b34b0

**In the Anvil GUI you can rename any item for 1 level when specified you need more.
As you can see I have 1 level, It doesn't work with less than 1
I can rename the item even though I don't have 7 levels**
https://gyazo.com/3e48058e5106735129e11f39f04af5d2
**_This could be because in 1.7 you need 7 levels for a normal diamond sword to be renamed
But in 1.8 it was changed to 1 level_**

**Comment by Gerrygames** [comment]
Hmm this is working for me. It shows 7 levels for a short moment and then switches to 1 level.

**Comment by Gerrygames** [comment]
Oh, it is working in 1.11.2 but not in 1.12.2. Hm.
