### ISSUE TITLE
Villager GUI

### ISSUE THREAD

**Issue by KiwiTerra** [Gerrygames/ViaRewind#4]
### What is the output link of /viaversion dump? 

https://gist.github.com/7c51070a06ad80aa395e915575bf67fa

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

No, I'm not use BungeeCord

Plugins: Viaversion, ViaBackwards ans ViaRewind

### How does this error happen? login? Using an item? 

Items in villager GUI ( http://prntscr.com/i20ltw )

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No. It work in 1.8 but it doesn't work in 1.7

**Comment by Gerrygames** [comment]
Thanks for reporting this bug. I will have a look at it.

**Comment by Gerrygames** [comment]
fixed
