### ISSUE TITLE
Add an option to disable 1.7 support

### ISSUE THREAD

**Issue by TrademarkTM** [Gerrygames/ViaRewind#46]
Hey!
My suggestion is basically what the title says, to add an option to completely disable 1.7 support. I am planning to add only 1.8, which seems to be more stable, so 1.7 is going to be completely useless.

Blocking 1.7 using ViaVersion would work the same way? Like, if there's going to be no difference, you can just close the thread.

Thanks!

**Comment by Gerrygames** [comment]
You can just disable it in the ViaVersion config with "block-protocols".
