### ISSUE TITLE
Book signing on 1.8.9 adds "\n" characters instead of new lines

### ISSUE THREAD

**Issue by Govindass** [Gerrygames/ViaRewind#47]
Hello, I have found a bug that when I sign a book on 1.8.9 weird characters get added, like "\n" for new line and some other for other symbols. If a book is signed with 1.11.2 client it works good, but 1.8 client signed books has the symbols and they are visible for all other versions. Using ViaRewind 1.1.5 and 1.11.2 Spigot

**Comment by Gerrygames** [comment]
fixed
