### ISSUE TITLE
1.7 not working properly. (1.7.10, and below.) [MAJOR ISSUE!]

### ISSUE THREAD

**Issue by R00tB33rMan** [Gerrygames/ViaRewind#50]
Server Versions Tested: Spigot 1.8.8, and Spigot 1.12.2.
It simply says it isn't supported, this is a MAJOR issue, and needs to be fixed right away.
Yes, I do have ViaVersion, and ViaBackwards installed on 1.12.2, and Vault + ProtocolLib.

**Comment by R00tB33rMan** [comment]
ViaBackwards was not installed on 1.8.8 Spigot test.

**Comment by Gerrygames** [comment]
Are you using BungeeCord? If yes you need to use a Proxy that supports 1.7.x.

**Comment by R00tB33rMan** [comment]
No, it’s a regular server, not BungeeCord.

**Comment by Gerrygames** [comment]
1.7 support is working for everyone else. Please provide the output of /viaversion debug.
