### ISSUE TITLE
Cant hear hit sounds

### ISSUE THREAD

**Issue by LinsaFTW** [Gerrygames/ViaRewind#51]
I cant hear the hit sounds when i hit other players , but i can hear my own when i get hit.

This happens when joining a 1.12.2 server with 1.7-1.8

**Comment by Gerrygames** [comment]
Yeah in 1.9 many sounds got clientside. There is no easy way to fix this. I don't think this will ever be fixed, sorry :/

**Comment by Gerrygames** [comment]
fixed in the upcoming update of ViaRewind Legacy Support
