### ISSUE TITLE
Internet lag with 1.8.9 client on 1.11.2 server

### ISSUE THREAD

**Issue by Govindass** [Gerrygames/ViaRewind#52]
I have noticed that I get unnormally high internet lag(when changing world mostly) when using 1.8.9 on 1.11.2 server, I do not get it with 1.11.2, I'm really close to server and I normally get 10-20ms ping, but when on 1.8.9 I happen to get over 100ms ping, this also happens for other players. I think this is something to-do with the way how viarewind works with packets? Ping becomes normal when not changing worlds, so it might be something to-do with chunk sending I think. there's currently like 1-3 seconds delay between you can do something after changing world when using 1.8.9.

**Comment by Gerrygames** [comment]
Yep it‘s due to the chunk packet transformation. I did already improve the remapping of the blocks. This change will be in the next release. I will probably release it today. Could you inform me if it works better with the new release, as soon as it is released?

**Comment by Govindass** [comment]
thanks, I will inform you

**Comment by DJMax486** [comment]
Hi there, I'm experiencing theses sames issues. I have a 1.8 spigot server and with the 1.7 client version, the server is lagging, the lags are now fewer, but always present.
It is possible to re-improve the block remapping ?

**Comment by Gerrygames** [comment]
Chunk remapping has been improved several times since this issue was closed. I think it should work fine now.
