### ISSUE TITLE
Player's position bug

### ISSUE THREAD

**Issue by KiwiTerra** [Gerrygames/ViaRewind#6]
KiwiTerra's version (Minecraft Right) : Forge 1.7.10
da_chicken's version (Minecraft Left) : LabyMod 1.8.9

Spigot version : This server is running CraftBukkit version git-Spigot-3d850ec-809c399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
BungeeCord : yes

Video : https://youtu.be/wp2AT4_FHk0

(This bug has been reported with ProtocolSupport but they do not have enough time to fix it and it also exists on ViaRewind)

**Comment by Gerrygames** [comment]
I guess this is just the normal behavior of Minecraft 1.7. I remember that this problem existed back in the days and almost every server had a /fix command.

**Comment by KiwiTerra** [comment]
And you can not correct it? : /

**Comment by Gerrygames** [comment]
Maybe, but I don't think I will do it.
