### ISSUE TITLE
Join, Absorption and Fire

### ISSUE THREAD

**Issue by oflords** [Gerrygames/ViaRewind#65]
https://i.imgur.com/hkGiXtj.png

Happens whenever a 1.7-1.8 player joins the server. Skins and tags are returned once they change worlds

Players cannot see fire on their screen in 1.7 but take damage

Players cannot see absorption hearts in 1.7 but have them and can see the effect.

Using tacospigot 1.8.8 with lastest ViaRewind (1.2.2) and ViaRewind Legacy Support (1.2.0)

**Comment by oflords** [comment]
Can confirm absorption hearts still cannot be seen on 1.7.10 in the newest version

**Comment by Gerrygames** [comment]
https://puu.sh/zrpAs/c66627bd96.png

**Comment by oflords** [comment]
Tried to re-install the plugin and still getting the same error.
Can you please send me that test server so I can check what the issue is?

**Comment by Gerrygames** [comment]
This is just my localhost server. It‘s a clean Spigot 1.12.2 server with ViaVersion, ViaBackwards and ViaRewind.

**Comment by oflords** [comment]
Ok as I said above I am using TacoSpigot 1.8.8 with ViaVersion, ViaRewind and ViaRewind Legacy Support. Are you able to test on that please?
