### ISSUE TITLE
Plotsquared "antisteal feature" and viarewind cause disconect

### ISSUE THREAD

**Issue by xion87** [Gerrygames/ViaRewind#73]
I have a paperspigot 1.12.2 with latest viarewind, viaversion, viabackard under Waterfall.
The server is creative mode and use plotsqured with plots.
The plotsquared plugin have a feature if player try to "steal" heads or banner, it will be replaced with regular heads/banner.
I never have this issue using protocolsupport, instead using viarewind and any client, it cause the player to disconect  if he try to "steal" (like the server was offline). 

I dont have any logs, on console, it just disconect message.

**Comment by Gerrygames** [comment]
If this happens on any client this is not caused by ViaRewind.

**Comment by xion87** [comment]
so viaversion bug?

**Comment by Gerrygames** [comment]
If it is happening with every version (even 1.12.2) this will not be related to any protocol hack plugin.

**Comment by xion87** [comment]
i just upgraded to viaversion/viarewind from protocolsupport and this happening

**Comment by Gerrygames** [comment]
Is it happening with 1.12.2 clients?

**Comment by xion87** [comment]
yes with all clients

**Comment by Gerrygames** [comment]
then it is not related to any protocol hack

**Comment by xion87** [comment]
I confirm that using protocolsupport it don't crash the client and working correct, it can be a plotsquared issue?

**Comment by xion87** [comment]
I opened the issue here https://github.com/IntellectualSites/PlotSquared/issues/1888
