### ISSUE TITLE
boat on 1.8.9

### ISSUE THREAD

**Issue by mihapain1** [Gerrygames/ViaRewind#89]
client 1.8.9 
server 1.12.2

> https://dump.viaversion.com/c64704bcec7c9f4f09b7123ca69d381c3851fee3ef272d2ab40d67cf9605557c

1. When a player leaves the boat, he teleports back to the place where he started his voyage.

2. Also boats do not work on ice

**Comment by Gerrygames** [comment]
This is unfortunately a known issue and can't be fixed without editing the Spigot/Minecraft server source.
