### ISSUE TITLE
Fire damage sound (1.8.9)

### ISSUE THREAD

**Issue by mihapain1** [Gerrygames/ViaRewind#90]
client 1.8.9
server 1.12.2

> https://dump.viaversion.com/948ec19c98552f105fea52f724abd2c00b35c7e7610179e8967e7c803a096d26

There is no sound if fire damage is received on version 1.8.9

**Comment by Gerrygames** [comment]
Some sound are client side since 1.9. ViaRewind Legacy Support should fix this issue.
