### ISSUE TITLE
Purpur slabs are shown incorrectly (1.8.9)

### ISSUE THREAD

**Issue by mihapain1** [Gerrygames/ViaRewind#91]
client 1.8.9
server 1.12.2

> https://dump.viaversion.com/948ec19c98552f105fea52f724abd2c00b35c7e7610179e8967e7c803a096d26
![default](https://user-images.githubusercontent.com/38764610/45491089-7f50f680-b771-11e8-88c4-721add127d28.png)

**Comment by Lmmb74** [comment]
That's because the purpur blocks do not exist in Minecraft 1.8.9. So ViaRewind makes it look different for the client, since there is no item or texture like such in any pre-1.9 version.

**Comment by mihapain1** [comment]
You did not understand. The purpur slab located at the top position is displayed in the bottom position

![default](https://user-images.githubusercontent.com/38764610/45506331-8f7bcc80-b797-11e8-9f3c-32027930ff58.png)

**Comment by Lmmb74** [comment]
Ahhhhhh, sorry u.u
