### ISSUE TITLE
1.7 cannot join 1.8 server after latest viaversion update

### ISSUE THREAD

**Issue by PhanaticD** [Gerrygames/ViaRewind#93]
as title says, with vanilla 1.7.10 client i just get PhanaticD lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

**Comment by Gerrygames** [comment]
I‘ll have to update ViaRewind to make it compatible to the latest ViaVersion update. There were a lot of internal changes.

**Comment by Gerrygames** [comment]
fixed
