### ISSUE TITLE
1.12.2 Server: Chunks are not always loading on 1.8.x Clients

### ISSUE THREAD

**Issue by zLucPlayZ** [Gerrygames/ViaRewind#95]
I noticed that everyone that uses 1.8.x Clients complain about chunks that are not perfectly loading... I can see that box around blocks in there, and if I destroy one of them, this chunk is going to be displayed. Hit me if this is not a bug, but pls tell me how to fix it ^^ (If its not a bug auf ViaVersion, ViaBackwards, Viarewind)

(Mostly happens in the Lobby, when the player joins)

**Comment by Gerrygames** [comment]
Just press F3+A to reload chunks. It's a 1.8 client issue.
