### ISSUE TITLE
Red sandstone slabs are shown incorrectly (1.7.10)

### ISSUE THREAD

**Issue by mihapain1** [Gerrygames/ViaRewind#98]
client 1.7.10
server 1.12.2

Red sandstone slab located at the top position is displayed in the bottom position

> https://dump.viaversion.com/be2fc43519d0d92a6d11ff9cc73e2b6d732505b5c37cabd38e331238560b2a9e
![default](https://user-images.githubusercontent.com/38764610/47103729-8378a400-d248-11e8-900b-03f78e63ec8b.png)

**Comment by Gerrygames** [comment]
You can download the fixed version here:
https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/10/
